FROM mcr.microsoft.com/mssql/server:2019-CTP3.0-ubuntu

RUN mkdir /var/opt/sqlserver

COPY DatabaseA.mdf /var/opt/sqlserver
COPY DatabaseA_log.ldf /var/opt/sqlserver

COPY attach-db.sh /var/opt/sqlserver

ENV MSSQL_BACKUP_DIR="/var/opt/sqlserver"
ENV MSSQL_DATA_DIR="/var/opt/sqlserver"
ENV MSSQL_LOG_DIR="/var/opt/sqlserver"

RUN chmod +x /var/opt/sqlserver/attach-db.sh

ENTRYPOINT /var/opt/sqlserver/attach-db.sh & /opt/mssql/bin/sqlservr